/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package kitchen_system;

/**
 *
 * @author Adam
 */
public class Kitchen_Screen extends javax.swing.JFrame {

    /**
     * Creates new form Kitchen_Screen
     */
    public Kitchen_Screen() {
        initComponents();
        orderPanel1_OrderUpdates.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        orderPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        orderNumber1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        orderPanel1_OrderStatus = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        orderPanel1_OrderTimer = new javax.swing.JTextField();
        orderPanel1_ScrollPane = new javax.swing.JScrollPane();
        orderPanel1_Order = new javax.swing.JList<>();
        orderPanel1_OrderUpdates = new javax.swing.JPanel();
        javax.swing.JButton orderPanel1_Prepping = new javax.swing.JButton();
        orderPanel1_Ready = new javax.swing.JButton();
        orderPanel2 = new javax.swing.JPanel();
        jToolBar3 = new javax.swing.JToolBar();
        orderNumber2 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        orderPanel2_OrderStatus = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        orderPanel2_OrderTimer = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        orderPanel2_Order = new javax.swing.JList<>();
        orderPanel3 = new javax.swing.JPanel();
        jToolBar6 = new javax.swing.JToolBar();
        jLabel4 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JToolBar.Separator();
        jTextField8 = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JToolBar.Separator();
        jTextField9 = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jToolBar4 = new javax.swing.JToolBar();
        jLabel2 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        jTextField4 = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        jTextField5 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jToolBar5 = new javax.swing.JToolBar();
        jLabel3 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JToolBar.Separator();
        jTextField6 = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JToolBar.Separator();
        jTextField7 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jToolBar7 = new javax.swing.JToolBar();
        jLabel5 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JToolBar.Separator();
        jTextField10 = new javax.swing.JTextField();
        jSeparator14 = new javax.swing.JToolBar.Separator();
        jTextField11 = new javax.swing.JTextField();
        kitchenScreen_HeadingBar = new javax.swing.JToolBar();
        jTextField1 = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jTextField3 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jButton1 = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        orderPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jToolBar1.setBackground(new java.awt.Color(153, 153, 153));
        jToolBar1.setRollover(true);

        orderNumber1.setText("1");
        jToolBar1.add(orderNumber1);
        jToolBar1.add(jSeparator1);

        orderPanel1_OrderStatus.setEditable(false);
        orderPanel1_OrderStatus.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        orderPanel1_OrderStatus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orderPanel1_OrderStatusMouseClicked(evt);
            }
        });
        orderPanel1_OrderStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderPanel1_OrderStatusActionPerformed(evt);
            }
        });
        jToolBar1.add(orderPanel1_OrderStatus);
        jToolBar1.add(jSeparator2);

        orderPanel1_OrderTimer.setEditable(false);
        orderPanel1_OrderTimer.setText("00:00");
        jToolBar1.add(orderPanel1_OrderTimer);

        orderPanel1_Order.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        orderPanel1_Order.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        orderPanel1_Order.setToolTipText("");
        orderPanel1_Order.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orderPanel1_OrderMouseClicked(evt);
            }
        });
        orderPanel1_ScrollPane.setViewportView(orderPanel1_Order);

        orderPanel1_OrderUpdates.setEnabled(false);
        orderPanel1_OrderUpdates.setFocusable(false);

        orderPanel1_Prepping.setText("Prepping");
        orderPanel1_Prepping.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orderPanel1_PreppingMouseClicked(evt);
            }
        });

        orderPanel1_Ready.setText("Ready");

        javax.swing.GroupLayout orderPanel1_OrderUpdatesLayout = new javax.swing.GroupLayout(orderPanel1_OrderUpdates);
        orderPanel1_OrderUpdates.setLayout(orderPanel1_OrderUpdatesLayout);
        orderPanel1_OrderUpdatesLayout.setHorizontalGroup(
            orderPanel1_OrderUpdatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(orderPanel1_OrderUpdatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(orderPanel1_OrderUpdatesLayout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(orderPanel1_Prepping)
                    .addContainerGap(13, Short.MAX_VALUE)))
            .addGroup(orderPanel1_OrderUpdatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, orderPanel1_OrderUpdatesLayout.createSequentialGroup()
                    .addContainerGap(18, Short.MAX_VALUE)
                    .addComponent(orderPanel1_Ready)
                    .addContainerGap(19, Short.MAX_VALUE)))
        );
        orderPanel1_OrderUpdatesLayout.setVerticalGroup(
            orderPanel1_OrderUpdatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 195, Short.MAX_VALUE)
            .addGroup(orderPanel1_OrderUpdatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(orderPanel1_OrderUpdatesLayout.createSequentialGroup()
                    .addGap(63, 63, 63)
                    .addComponent(orderPanel1_Prepping, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(99, Short.MAX_VALUE)))
            .addGroup(orderPanel1_OrderUpdatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, orderPanel1_OrderUpdatesLayout.createSequentialGroup()
                    .addContainerGap(132, Short.MAX_VALUE)
                    .addComponent(orderPanel1_Ready)
                    .addContainerGap(40, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout orderPanel1Layout = new javax.swing.GroupLayout(orderPanel1);
        orderPanel1.setLayout(orderPanel1Layout);
        orderPanel1Layout.setHorizontalGroup(
            orderPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
            .addComponent(orderPanel1_ScrollPane)
            .addGroup(orderPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(orderPanel1Layout.createSequentialGroup()
                    .addGap(76, 76, 76)
                    .addComponent(orderPanel1_OrderUpdates, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(77, Short.MAX_VALUE)))
        );
        orderPanel1Layout.setVerticalGroup(
            orderPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orderPanel1_ScrollPane))
            .addGroup(orderPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(orderPanel1Layout.createSequentialGroup()
                    .addGap(57, 57, 57)
                    .addComponent(orderPanel1_OrderUpdates, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(55, Short.MAX_VALUE)))
        );

        orderPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jToolBar3.setRollover(true);

        orderNumber2.setText("2");
        jToolBar3.add(orderNumber2);
        jToolBar3.add(jSeparator5);

        orderPanel2_OrderStatus.setEditable(false);
        orderPanel2_OrderStatus.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        orderPanel2_OrderStatus.setText("Active");
        jToolBar3.add(orderPanel2_OrderStatus);
        jToolBar3.add(jSeparator6);

        orderPanel2_OrderTimer.setEditable(false);
        orderPanel2_OrderTimer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        orderPanel2_OrderTimer.setText("00:00");
        jToolBar3.add(orderPanel2_OrderTimer);

        orderPanel2_Order.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(orderPanel2_Order);

        javax.swing.GroupLayout orderPanel2Layout = new javax.swing.GroupLayout(orderPanel2);
        orderPanel2.setLayout(orderPanel2Layout);
        orderPanel2Layout.setHorizontalGroup(
            orderPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar3, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
            .addComponent(jScrollPane5)
        );
        orderPanel2Layout.setVerticalGroup(
            orderPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderPanel2Layout.createSequentialGroup()
                .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5)
                .addContainerGap())
        );

        orderPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jToolBar6.setRollover(true);

        jLabel4.setText("3");
        jToolBar6.add(jLabel4);
        jToolBar6.add(jSeparator11);

        jTextField8.setEditable(false);
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField8.setText("Active");
        jToolBar6.add(jTextField8);
        jToolBar6.add(jSeparator12);

        jTextField9.setEditable(false);
        jTextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField9.setText("00:00");
        jToolBar6.add(jTextField9);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane7.setViewportView(jList1);

        javax.swing.GroupLayout orderPanel3Layout = new javax.swing.GroupLayout(orderPanel3);
        orderPanel3.setLayout(orderPanel3Layout);
        orderPanel3Layout.setHorizontalGroup(
            orderPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar6, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
        );
        orderPanel3Layout.setVerticalGroup(
            orderPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderPanel3Layout.createSequentialGroup()
                .addComponent(jToolBar6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 17, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        jToolBar4.setRollover(true);

        jLabel2.setText("4");
        jToolBar4.add(jLabel2);
        jToolBar4.add(jSeparator7);

        jTextField4.setEditable(false);
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("Active");
        jToolBar4.add(jTextField4);
        jToolBar4.add(jSeparator8);

        jTextField5.setEditable(false);
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText("00:00");
        jToolBar4.add(jTextField5);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar4, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jToolBar4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 224, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addGap(0, 29, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane4.setViewportView(jTextArea3);

        jToolBar5.setRollover(true);

        jLabel3.setText("5");
        jToolBar5.add(jLabel3);
        jToolBar5.add(jSeparator9);

        jTextField6.setEditable(false);
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.setText("Active");
        jToolBar5.add(jTextField6);
        jToolBar5.add(jSeparator10);

        jTextField7.setEditable(false);
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField7.setText("00:00");
        jToolBar5.add(jTextField7);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
            .addComponent(jToolBar5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jToolBar5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextArea5.setColumns(20);
        jTextArea5.setRows(5);
        jScrollPane6.setViewportView(jTextArea5);

        jToolBar7.setRollover(true);

        jLabel5.setText("6");
        jToolBar7.add(jLabel5);
        jToolBar7.add(jSeparator13);

        jTextField10.setEditable(false);
        jTextField10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField10.setText("Active");
        jToolBar7.add(jTextField10);
        jToolBar7.add(jSeparator14);

        jTextField11.setEditable(false);
        jTextField11.setText("00:00");
        jToolBar7.add(jTextField11);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar7, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jToolBar7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 224, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                    .addGap(0, 33, Short.MAX_VALUE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        kitchenScreen_HeadingBar.setBorder(new javax.swing.border.MatteBorder(null));
        kitchenScreen_HeadingBar.setRollover(true);

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        kitchenScreen_HeadingBar.add(jTextField1);
        kitchenScreen_HeadingBar.add(jSeparator4);

        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        kitchenScreen_HeadingBar.add(jTextField3);
        kitchenScreen_HeadingBar.add(jSeparator3);

        jButton1.setText("Managment");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        kitchenScreen_HeadingBar.add(jButton1);

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane8.setViewportView(jList2);

        jLabel6.setBackground(new java.awt.Color(255, 102, 102));
        jLabel6.setText("Pending Orders");
        jLabel6.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(kitchenScreen_HeadingBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(orderPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(orderPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(orderPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(jScrollPane8)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(kitchenScreen_HeadingBar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(orderPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(orderPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(orderPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(37, 37, 37))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane8))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void orderPanel1_OrderStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderPanel1_OrderStatusActionPerformed
  
    }//GEN-LAST:event_orderPanel1_OrderStatusActionPerformed

    private void orderPanel1_OrderStatusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderPanel1_OrderStatusMouseClicked

    }//GEN-LAST:event_orderPanel1_OrderStatusMouseClicked

    private void orderPanel1_PreppingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderPanel1_PreppingMouseClicked
       
orderPanel1_ScrollPane.setVisible(true);
orderPanel1_OrderUpdates.setVisible(false);
orderPanel1_OrderStatus.setText("Prepping");

    }//GEN-LAST:event_orderPanel1_PreppingMouseClicked

    private void orderPanel1_OrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderPanel1_OrderMouseClicked
  orderPanel1_ScrollPane.setVisible(false);
orderPanel1_OrderUpdates.setVisible(true);
    }//GEN-LAST:event_orderPanel1_OrderMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kitchen_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kitchen_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kitchen_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kitchen_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Kitchen_Screen().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator10;
    private javax.swing.JToolBar.Separator jSeparator11;
    private javax.swing.JToolBar.Separator jSeparator12;
    private javax.swing.JToolBar.Separator jSeparator13;
    private javax.swing.JToolBar.Separator jSeparator14;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JToolBar.Separator jSeparator9;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JToolBar jToolBar4;
    private javax.swing.JToolBar jToolBar5;
    private javax.swing.JToolBar jToolBar6;
    private javax.swing.JToolBar jToolBar7;
    private javax.swing.JToolBar kitchenScreen_HeadingBar;
    private javax.swing.JLabel orderNumber1;
    private javax.swing.JLabel orderNumber2;
    private javax.swing.JPanel orderPanel1;
    private javax.swing.JList<String> orderPanel1_Order;
    private javax.swing.JTextField orderPanel1_OrderStatus;
    private javax.swing.JTextField orderPanel1_OrderTimer;
    private javax.swing.JPanel orderPanel1_OrderUpdates;
    private javax.swing.JButton orderPanel1_Ready;
    private javax.swing.JScrollPane orderPanel1_ScrollPane;
    private javax.swing.JPanel orderPanel2;
    private javax.swing.JList<String> orderPanel2_Order;
    private javax.swing.JTextField orderPanel2_OrderStatus;
    private javax.swing.JTextField orderPanel2_OrderTimer;
    private javax.swing.JPanel orderPanel3;
    // End of variables declaration//GEN-END:variables
}
