//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HangmansPizzaAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CUSTOMER()
        {
            this.ADDRESSes = new HashSet<ADDRESS>();
            this.ORDERS = new HashSet<ORDER>();
        }
    
        public int CUSTOMER_ID { get; set; }
        public string CUSTOMER_TITLE { get; set; }
        public string CUSTOMER_FORENAME { get; set; }
        public string CUSTOMER_SURNAME { get; set; }
        public string CUSTOMER_EMAIL { get; set; }
        public string CUSTOMER_PHONE { get; set; }
        public string CUSTOMER_PASSWORD { get; set; }
        public System.DateTime CUSTOMER_DOB { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADDRESS> ADDRESSes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER> ORDERS { get; set; }
    }
}
