//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HangmansPizzaAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DELIVERY_RIDER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DELIVERY_RIDER()
        {
            this.DELIVERies = new HashSet<DELIVERY>();
            this.RIDER_ACTIVITY = new HashSet<RIDER_ACTIVITY>();
        }
    
        public int RIDER_ID { get; set; }
        public string RIDER_FORENAME { get; set; }
        public string RIDER_SURNAME { get; set; }
        public string RIDER_EMAIL { get; set; }
        public string RIDER_PHONE { get; set; }
        public string RIDER_PASSWORD { get; set; }
        public string VEHICLE_TYPE { get; set; }
        public System.DateTime RIDER_DOB { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DELIVERY> DELIVERies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RIDER_ACTIVITY> RIDER_ACTIVITY { get; set; }
    }
}
