//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HangmansPizzaAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INGREDIENT
    {
        public int INGREDIENT_ID { get; set; }
        public int INGREDIENT_TYPE_ID { get; set; }
        public int STOCK { get; set; }
        public string UNIT_PRICE { get; set; }
        public bool VEGETARIAN { get; set; }
        public bool VEGAN { get; set; }
    
        public virtual INGREDIENT_TYPE INGREDIENT_TYPE { get; set; }
    }
}
