//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HangmansPizzaAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PIZZA_INGREDIENT
    {
        public int PIZZA_ID { get; set; }
        public int INGREDIENT_ID { get; set; }
        public short QUANTITY_USED { get; set; }
    }
}
