//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HangmansPizzaAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIDE
    {
        public int SIDE_ID { get; set; }
        public int ITEM_ID { get; set; }
        public int STOCK { get; set; }
        public decimal UNIT_PRICE { get; set; }
    
        public virtual ITEM ITEM { get; set; }
    }
}
