//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HangmansPizzaAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMIN
    {
        public int ADMIN_ID { get; set; }
        public int BRANCH_ID { get; set; }
        public string FORENAME { get; set; }
        public string SURNAME { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public string PASSWORD_SALT { get; set; }
    }
}
