//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HangmansPizzaAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER
    {
        public int CUSTOMER_ID { get; set; }
        public string CUSTOMER_TITLE { get; set; }
        public string CUSTOMER_FORENAME { get; set; }
        public string CUSTOMER_SURNAME { get; set; }
        public string CUSTOMER_EMAIL { get; set; }
        public string CUSTOMER_PHONE { get; set; }
        public string CUSTOMER_PASSWORD { get; set; }
        public System.DateTime CUSTOMER_DOB { get; set; }
        public int ADDRESS_ID { get; set; }
    }
}
