//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HangmansPizzaAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class DELIVERY_RIDER
    {
        public int RIDER_ID { get; set; }
        public string RIDER_FORENAME { get; set; }
        public string RIDER_SURNAME { get; set; }
        public string RIDER_EMAIL { get; set; }
        public string RIDER_PHONE { get; set; }
        public string RIDER_PASSWORD { get; set; }
        public string VEHICLE_TYPE { get; set; }
        public System.DateTime RIDER_DOB { get; set; }
        public string RIDER_TITLE { get; set; }
    }
}
