//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HangmansPizzaAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class INGREDIENT_TYPE
    {
        public int INGREDIENT_TYPE_ID { get; set; }
        public string INGREDIENT_TYPE1 { get; set; }
        public string DESCRIPTION { get; set; }
    }
}
