//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HangmansPizzaAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENU_ITEM
    {
        public int MENU_ID { get; set; }
        public int ITEM_ID { get; set; }
        public short QUANTITY { get; set; }
        public decimal UNIT_PRICE { get; set; }
    }
}
