//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HangmansPizzaAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER_ITEM
    {
        public int ITEM_ID { get; set; }
        public int ORDER_ID { get; set; }
        public int QUANTITY { get; set; }
        public string UNIT_PRICE { get; set; }
        public string ITEM_SIZE { get; set; }
        public string ITEM_CRUSTTYPE { get; set; }
    }
}
