//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HangmansPizzaAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER
    {
        public int ORDER_ID { get; set; }
        public int CUSTOMER_ID { get; set; }
        public System.DateTime DATE_PLACED { get; set; }
        public System.DateTime DATE_REQUESTED { get; set; }
        public decimal TOTAL_COST { get; set; }
        public string ORDER_TYPE { get; set; }
        public string NOTES { get; set; }
    }
}
